/**
 * @microbuild/utils
 * 
 * Utility functions for Microbuild UI packages.
 * Includes field interface mapping, value formatting, and validation helpers.
 */

// Field Interface Mapper
export {
  getFieldInterface,
  getFieldDefault,
  getFieldValidation,
  formatFieldValue,
  isFieldReadOnly,
  isUUIDAutoGenerated,
  hasAutoGeneratedDefault,
  getAutoGenerationType,
  isPresentationField,
  type InterfaceType,
  type InterfaceConfig,
  type FieldReadOnlyOptions,
} from './field-interface-mapper';
