/**
 * Item Edit/Create Page
 *
 * Renders a dynamic form for creating or editing a single item in a collection.
 * Uses CollectionForm (which wraps VForm with all 40+ field interfaces).
 *
 * Generated by @buildpad/cli
 */

"use client";

import React, { use } from 'react';
import { useRouter } from 'next/navigation';
import { CollectionForm } from '@/components/ui/collection-form';

export default function ItemPage({
  params,
}: {
  params: Promise<{ collection: string; id: string }>;
}) {
  const { collection, id } = use(params);
  const router = useRouter();

  const isNew = id === '+' || id === 'new';

  return (
    <CollectionForm
      collection={collection}
      id={isNew ? undefined : id}
      mode={isNew ? 'create' : 'edit'}
      onSuccess={() => router.push(`/content/${collection}`)}
      onCancel={() => router.back()}
    />
  );
}
