/**
 * Collection List Page
 *
 * Displays a table of items for the given collection with search,
 * filtering, pagination, selection, and bulk actions.
 *
 * Generated by @microbuild/cli
 */

"use client";

import React, { use, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Button, Group } from '@mantine/core';
import { IconPlus, IconTrash } from '@tabler/icons-react';
import { CollectionList } from '@/components/ui/collection-list';
import { useLocalStorage } from '@/lib/microbuild/hooks';
import type { BulkAction } from '@/components/ui/collection-list';

export default function CollectionPage({
  params,
}: {
  params: Promise<{ collection: string }>;
}) {
  const { collection } = use(params);
  const router = useRouter();
  const { setValue: setLastAccessed } = useLocalStorage<string>('last-accessed-collection');

  // Track last accessed collection
  useEffect(() => {
    setLastAccessed(collection);
  }, [collection, setLastAccessed]);

  const bulkActions: BulkAction[] = [
    {
      label: 'Delete',
      icon: <IconTrash size={16} />,
      color: 'red',
      action: async (selectedIds) => {
        if (!confirm(`Delete ${selectedIds.length} item(s)?`)) return;
        try {
          await fetch(`/api/items/${collection}`, {
            method: 'DELETE',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(selectedIds),
          });
          // CollectionList will auto-refresh
          window.location.reload();
        } catch (error) {
          console.error('Batch delete failed:', error);
        }
      },
    },
  ];

  return (
    <CollectionList
      collection={collection}
      enableSearch
      enableSelection
      bulkActions={bulkActions}
      onItemClick={(item) => router.push(`/content/${collection}/${item.id}`)}
    />
  );
}
